@url = https://sturdy-pancake-xggwqgx4qq9h64j6-8080.app.github.dev

GET {{url}}/colaboradores

###
POST {{url}}/colaboradores
Content-Type: application/json

{
    "nome": "Lara",
    "tarefas" : [
        {"id_tarefa": 3},
        {"id_tarefa": 4}
    ]
}

###
PUT {{url}}/colaboradores/1
Content-Type: application/json

{
    "nome": "Claudio",
    "tarefas" : [
        {"id_tarefa": 2}
    ]
}

###
DELETE {{url}}/colaboradores/5