@url = https://sturdy-pancake-xggwqgx4qq9h64j6-8080.app.github.dev

GET {{url}}/colaboradores

###
POST {{url}}/colaboradores
Content-Type: application/json

{
    "nome": "José",
    "tarefas" : [
        
    ]
}

###
PUT {{url}}/questoes/4
Content-Type: application/json

{
    "enunciado": "Questão com Categoria Novo Tese - Alterada",
    "categoria" : {
        "id": 4
    }
}

###
DELETE {{url}}/questoes/1